"""Rule-based PDF report with ReportLab."""
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Table, TableStyle, Image, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from ..core.config import THRESHOLDS

DISCLAIMER = ("This report was generated by an AI decision-support prototype for research purposes. "
              "It is not a diagnosis and must be reviewed by a qualified radiologist.")


def build_report(path, exam_id, patient_ref, predictions: dict, gradcam_paths: dict):
    st = getSampleStyleSheet(); doc = SimpleDocTemplate(path, pagesize=A4); el = []
    el += [Paragraph("Knee MRI AI Analysis Report", st["Title"]),
           Paragraph(f"Exam ID: {exam_id} &nbsp;&nbsp; Patient ref: {patient_ref or '-'}", st["Normal"]), Spacer(1, 12)]
    rows = [["Finding", "Confidence", "Flag"]] + [[k.upper(), f"{v:.1%}", "POSITIVE" if v >= THRESHOLDS[k] else "negative"] for k, v in predictions.items()]
    t = Table(rows, hAlign="LEFT"); t.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey), ("GRID", (0, 0), (-1, -1), 0.5, colors.grey)]))
    el += [t, Spacer(1, 12)]
    for label, p in gradcam_paths.items():
        el += [Paragraph(f"Grad-CAM: {label}", st["Heading3"]), Image(p, width=200, height=200), Spacer(1, 8)]
    el += [Spacer(1, 12), Paragraph(DISCLAIMER, st["Italic"])]
    doc.build(el)
